services:
  - type: web
    name: synapseBridge-frontend
    env: static
    staticPublishPath: ./dist
    routes:
     - type: rewrite
        source: /api/*  # Exclude API routes from being rewritten
        destination: /api/*  # Keep them as they are
      - type: rewrite
        source: /*
        destination: /index.html